### ISSUE TITLE
Minor UI improvement - Add New Cascade button

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#1044]
On the cascade resources screen:

![screen shot 2014-12-18 at 20 32 38](https://cloud.githubusercontent.com/assets/3003031/5495382/0a8bc696-86f5-11e4-95d4-1c952eccb159.png)

When the user clicks the central button, the text box top right is enabled to allow them to enter a name etc and save that. However at the moment I think if a user arrives at that screen and clicks the middle button it's not readily apparent that they should then click to the top right text box?

please close & ignore if we think it's clear as is

**Comment by joycarpediem** [comment]
@loicsans /@Kiarii, maybe we can remove the "Add new cascade " button on the top right as we have two buttons doing the same thing on the same page and bring the text box in the middle of the page. Also i've seen users struggling with the top right text box. Thoughts ?

**Comment by Kiarii** [comment]
@janagombitova could you comment on the priority of this issue

I think the button in the middle should be removed and on Clicking the "+ Add New Cascade" the user should be taken to the New/Edit Cascade creation page; the in between function "naming the cascade and saving it" so one can edit the cascade is also unnecessary and makes the user journey an extra step longer.

The " + Add New Cascade " should be simply rephrased to "+ Cascade", or "Add Cascade", or "New Cascade". "+/Plus", "Add" and "New" imply the same action - such repetition is redundant and does not simplify things logically or otherwise

**Comment by janagombitova** [comment]
I agree with Kiarii, that we should remove the button in the middle. All our "add" buttons are located in the top right corner and we should try to maintain the same location of actions throughout the entire tool. 

Second, I also think the "naming" step is unnecessary. 

Third, I also agree Kiarii with you also on the double emphasis we put on add with the word and the + icon. But if we change it here, we need to change it everywhere. I think it is wise to add this change, to the work that will be done on re-designing the survey creation path.  

I do not see it as a strong priority, but we should fix it. So, let's work on these two steps in August/September and leave the third one for later iterations.

**Comment by janagombitova** [comment]
Solution for now: Remove the middle 'add' button 

Regarding the changes in UX - we will tackle this later as part of larger UX changes on the dashboard

**Comment by gabemart** [comment]
### Test plan

1) Navigate to Data > Cascade Resources

2) Verify that no "Add New Cascade" button appears below "Please select an existing cascade resource..."

**Comment by rumca** [comment]
Test plan passes as described.
