### ISSUE TITLE
Improve selecting survey using hierarchical dropdowns

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#1053]
At the moment, in the data tab and survey tabs, when a single survey or form needs to be selected, the user is presented with a long list of all surveys. This is not very user friendly.

Proposed solution: 
Use a sequence of coupled dropdowns which a user can use to select a survey from within a specific folder, just as is used in the roles tab.

**Comment by jonase** [comment]
@loicsans Could you check the UI for this?

**Comment by jonase** [comment]
@loicsans You will probably need a few classes to hook into. The structure of the hierarchical survey selection is

```
<div>
  <select>...</select>
  <select>...</select>
  <select>...</select>
</div>
```

where each `select` is a level in folder/survey hierarchy. Let me know what you need and I'll add it.

**Comment by jonase** [comment]
## Test plan

There are five places where we use this new feature

* Data > Inspect Data
* Data > Data Cleaning
* Data > Monitoring
* Reports > Charts
* Reports > Export Reports

and the feature should work the same across these different places.

* Select a survey by using the dropdowns. If you select a folder instead of a survey another dropdown should appear which will contain the child folders/surveys of the selected folder. It should be possible to select any survey as long as you know the path.
* If the task is to select a form (or a question) the list of forms should be populated when a survay (as opposed to a folder) is selected. If another survey is selected the forms dropdown should update as well.

**Comment by iperdomo** [comment]
As agreed, we want to _lead_ the user picking a form/survey from the hierarchy. We'll hide some dropdowns until they are usable, e.g. no `Form` dropdown until you have selected a `Survey` in the Data tab, etc

**Comment by rumca** [comment]
Tested and mostly works as expected - there's still some empty folders appearing in the drop downs: 

![screen shot 2015-01-28 at 12 58 46](https://cloud.githubusercontent.com/assets/3003031/5937920/6f4e3984-a6ed-11e4-972e-b484181f0f19.png)

@jonase not sure how hard it would be to hide these?

**Comment by jonase** [comment]
@rumca do you mean by selecting an empty folder you simply wouldn't get the next dropdown? That might be a bit confusing I think. Right now you select a folder and notice that it's empty when there are no folders/surveys to choose from in the next dropdown. @loicsans what are your thoughts on this?

**Comment by rumca** [comment]
I was more thinking that we should just remove empty folders from the list all together - but that might be a bit more complicated.

**Comment by jonase** [comment]
@rumca I don't think that would be complicated to add. I'll open an issue scheduled for the next release.

**Comment by rumca** [comment]
@jonase as per comments on #1059, I think we ned to modify this slightly to allow for searching on the Monitoring tab

**Comment by rumca** [comment]
Not sure if this is relevant, but there's some merge conflict leftovers from this issue which need removed here also: https://github.com/akvo/akvo-flow/blob/dc53680afd2dcd51548891c7b9a6568cb7551324/Dashboard/app/js/templates/navData/monitoring-data.handlebars#L132

**Comment by iperdomo** [comment]
@rumca definitively, good catch

**Comment by rumca** [comment]
monitoring tab search drop downs now work correctly
