### ISSUE TITLE
Form names are no longer visible when many forms are present in a monitoring survey group

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1066]
When there is a large number of forms in a monitoring group, it is no longer possible to view the form names, making it impossible to identify which form one wants to edit.  See the screen shot for an example 

![screen shot 2015-01-12 at 14 44 38](https://cloud.githubusercontent.com/assets/533336/5703651/9fb80036-9a69-11e4-9e5b-563faeba645e.png)

**Comment by janagombitova** [comment]
This needs a more comprehensive UX solution. Open to options.

**Comment by gabemart** [comment]
My original proposed solution is to switch from tab layout to a dropdown menu when the number of forms is too great to display as tabs.

After experimenting with this, it is confusing to hit the "new form" button with a dropdown menu because, although the new form is added to the dropdown, you can only see this if you activate the dropdown. In other words, there is no immediate visual confirmation that a new form has been created.

I think that when a new form is created, we should always immediately navigate to that form. I think most users, after creating a new form, will want to immediately edit some details of that form. Having them manually navigate to the new form is unnecessary. 

@Kiarii what are your thoughts?

**Comment by Kiarii** [comment]
I agree with @Gabemart that on creating the New Form button the user should be taken directly to the new form. 

It is also important for the user to be able to see the form names in the survey even if these are many; the current tab navigation is problematic in this case; a thorough rethink is necessary to figure out a better form presentation. Navigation and orientation need some enhancing also for the group and question editing etc..

**Comment by gabemart** [comment]
@muloem @janagombitova Based on Kiarii's comments, perhaps instead of switching between a tab-based layout and a dropdown-menu depending on the number of forms, we should just always use a dropdown-based layout? Thoughts?

**Comment by muloem** [comment]
We should put some more thought into this as @janagombitova mentioned.  But I do agree that among the thing to include in there is navigating to the new form when its created.  Also I am not sure if the current default behaviour is to sort the tabs alphabetically but may be better to give the user options of how they want to sort them with the default being created data perhaps?

**Comment by janagombitova** [comment]
This issue is a bundle of multiple smaller problems: 
- new form not visible, if too many forms are in the survey 
- adding a new form does not open up the new form directly 
- the overall layout of the forms and surveys 
- how should forms be organised? 

We have broken down these issues into smaller and separate ones, so I have linked them and will be closing this one. 

https://github.com/akvo/akvo-flow/issues/1975
https://github.com/akvo/akvo-flow/issues/1981
https://github.com/akvo/akvo-flow/issues/1982
