### ISSUE TITLE
Monitoring surveys assignment process streamlining

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#1128]
@mtwestra @iperdomo @muloem please disregard this if it's not feasible/doesn't make sense.

During the last round of testing I created and assigned a monitored survey to my phone with 2 forms, as part of the testing I added another form to the survey and published that - mistakenly thinking that would then be picked up on the phone (which it wasn't since the original assignment is done on a per form basis, not a per survey basis). It wasn't immediately clear to me what the problem was - so took a while to figure out I needed to update the assignment or else download the form directly on the app. It also resulted in the situation whereby I was able to have a monitoring survey without a registration form.

Perhaps we could add something to the publishing task to update any relevant assignments if the form is part of a monitored survey?

**Comment by iperdomo** [comment]
@rumca we can "hint" the user, and ask, but we cannot automatically update a valid assignment. AFAIK, we keep the assignment at form level because there will be cases when a user will get a _partial_ set of the forms of a monitoring survey.

**Comment by janagombitova** [comment]
Agree with @iperdomo comment and we do have cases in the field where users are assigned only a particular form to fill in. For example:
- because the other monitoring forms are to be submitted later in time 
- because of sampling of data points - enumerator has a list of points he has to re-visit and they need to have one extra monitoring form submitted and the assignment only contains that form to avoid confusion
- etc

Thus closing this issue
