### ISSUE TITLE
Buttons ADD DEVICE TO GROUP & REMOVE DEVICE FROM GROUP Not showing

### ISSUE THREAD

**Issue by andrewmolo** [akvo/akvo-flow#1273]
**Problem**
Under Devices tab, action buttons **ADD DEVICE TO GROUP** & **REMOVE DEVICE FROM GROUP**  do not show  after scrolling down the device list. 

![screen shot 2015-05-13 at 11 40 09](https://cloud.githubusercontent.com/assets/1729842/7607048/0ca7d3e0-f967-11e4-9673-e4750b953766.png)
![screen shot 2015-05-13 at 11 40 18](https://cloud.githubusercontent.com/assets/1729842/7607049/0ca8a5fe-f967-11e4-84b9-2549efaf25e9.png)

**Solution**
The buttons should appear while scrolling down the list.

**Comment by gabemart** [comment]
Should the "Manage device groups" button also be viewable after scrolling down the device list?

I can make the position of the buttons fixed as the user scrolls down the screen, which will make them accessible, but I will also need to change the styling of the buttons to make them more visible against the more varied background. Perhaps the "Add device to group" and "Remove device from group" buttons should be styled in the same way as the "Manage device groups" button, with a solid blue background?

Alternatively, I can just make the entire row of all three buttons fixed in place as the user scrolls down.

@loicsans any thoughts on this?

**Comment by loicsans** [comment]
@gabemart, you'd have to make the whole row of button positioning fixed, and add a white background to the whole row. By doing this you'd have to add quite a bit of margin and play with z-index. Let me know if you want me to have a look at this.

**Comment by gabemart** [comment]
![mediocrevengefulfiddlercrab](https://cloud.githubusercontent.com/assets/2589977/9382198/69356984-4736-11e5-978e-e98d4ad175b5.gif)

**Comment by gabemart** [comment]
### Test plan

1) Open the Devices tab

2) Scroll down the page

3) Verify that the "Manage device groups", "add to device group" and "remove from device group" buttons remain visible in a fixed position

4) Verify that the same buttons are clickable

**Comment by rumca** [comment]
test plan passes as described
