### ISSUE TITLE
Quick UI Fix - Positioning on save button for Question Group name

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#1419]
On the edit survey screen, when you select to edit a question group name, the positioning on the save button seems to have gone a bit skew-whiff. It used to be inline with the field but is now below it:

![screen shot 2015-09-30 at 09 22 14](https://cloud.githubusercontent.com/assets/3003031/10209885/51a56b9e-67d8-11e5-95f2-bf95eb74ea74.png)

**Comment by gabemart** [comment]
I think this change is intentional. The "Save" button applies both to changes in the group name and to changes in the "repeat question group" status of the question. making the save button inline with the group name makes it confusing when editing the "repeat question group" status, because then the "save" button appears before the checkbox it applies to.

It would be possible to separate this functionality into a different button or dialog and keep the "Save" button just for editing the group name and display it inline, but this would take some more time to implement.

**Comment by janagombitova** [comment]
@gabemart 
1. Could you position the save button + cancel to the bottom of the 'edit group name' window? As we have when creating new questions. (Then it could be understood as it applies to the entire editing the user does here)  
2. Related to that, can you also quickly change 'edit group name' to 'Edit group'?

**Comment by gabemart** [comment]
@janagombitova done now

![image](https://cloud.githubusercontent.com/assets/2589977/10245206/4b704e94-68fd-11e5-9fdb-91ae95caa766.png)

![image](https://cloud.githubusercontent.com/assets/2589977/10245215/6394646a-68fd-11e5-89b2-b635cf9da13f.png)

![image](https://cloud.githubusercontent.com/assets/2589977/10245223/732bf69a-68fd-11e5-800e-dce384932c7d.png)

I have changed the text from "Edit group name" to "Edit group for English", but have left the other languages as they are.

**Comment by gabemart** [comment]
# Test Plan

1) Edit a survey that has a question group

2) Verify the text of edit button next to "hide questions" is "edit group"

3) Hit the edit button

4) Verify the "save" button appears below the input

5) Save, then hit "show questions", then toggle the "repeat this group" checkbox

6) Verify the "save" button appears below the "repeat this group" help text

**Comment by rumca** [comment]
test plan passes as described
