### ISSUE TITLE
Repeatable Question Groups - Add import functionality for data cleaning

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#1421]
As part of the RQGs work (#269) we should also allow users to edit responses from repeatable groups in the data cleaning tab, and import these successfully.

**Comment by rumca** [comment]
Also as part of this, could we remove blank lines from RQG reports where a repeat number has no data associated. So for example if a user fills out three groups on the app, and then deletes the middle one. The iteration ids in the QAS will be 0 and 2 - which results in data reports as follows:

![screen shot 2015-10-01 at 15 23 11](https://cloud.githubusercontent.com/assets/3003031/10223321/5d2fda44-6850-11e5-8e9e-a8c4cc2dc4a5.png)

**Comment by janagombitova** [comment]
### Test plan

**Preparation**
Create a survey with repeated question groups. Collect data. Each submission should hold a different number of repeated iterations. 

**Test 1**
1. Under the Data cleaning tab download a survey with repeated question groups.
2. In Excel change the data (spelling, number change, delete data from a cell), but do not change the report structure. 
3. Under the Data cleaning tab upload the edited report to the same survey. 
4. Check the Messages tab. There should be a confirmation message.
5. In the Inspect data tab verify that the import was successful, changes were added but not other data nor structure was compromised.
6. Verify the changes by downloading the raw data report. 

**Test 2**
1. Under the Data cleaning tab download the survey with repeated question groups.
2. In Excel delete one repeat iteration row. 
3. Under the Data cleaning tab upload the edited report to the same survey.
4. Check the messages tab. There should be a message stating that the upload was unsuccessful. 
5. In the Inspect data tab, verify that the import was unsuccessful and the repeat iteration was not deleted.

**Test 3**
1. Download the survey (A) with the repeated question groups under the data cleaning tab.
2. Select another survey (B) in the Data cleaning tab.
3. Upload the survey (A) to survey (B). 
4. Check the Messages tab. There should be a message stating that the report is not processed because it was uploaded against the wrong survey.
5. Download the raw data report from survey (B) and check that no data has been added to it, or no further changes were made. Check this also in the Inspect data tab.

**Test 4**
1. Create a non-monitored survey with a repeated question group, a few question set as data point name outside the repeated group and a geolocation question. 
2. Collect a few responses.
3. Download the report and save it.
4. Copy the survey, rename it and change the advanced setting to make it a monitoring survey. Set the 'copied' form as the registration form.
5. Export a raw data report from the registration form. It should be empty with no data collected. 
6. Copy the data from the first data report into this one, with the instance ID column left empty. 
7. Import this raw data report against the newly created registration form via Data cleaning tab. 
8. In the Inspect data tab check that the data is imported and the repeated question groups' structure is correct. 
9. Check that there are new data points created under the Monitoring tab. Check that the data point names are set correctly as well. 
10. Check that the data points appear on the map and that the responses are properly generated in the side menu after clicking on a data point.
11. Download a raw data report and check that the data, repeat iteration structure and the proper identifiers are set.

**Comment by muloem** [comment]
All work or RQG import has been handled under the original issue #269. Closing this one.

**Comment by rumca** [comment]
I think after discussion with @jonase Test Case 2 isn't correct, it should be possible to delete iterations by removing them from the raw data report.

Apart from that - the remaining test cases all pass :sweat: :tada:
