### ISSUE TITLE
Trim down timestamp a date inside the raw data report

### ISSUE THREAD

**Issue by Geerts** [akvo/akvo-flow#1496]
When answering a date questions in the app you only see a date. In the raw data report a timestamp is included. 

Current situation
04-11-2015 01:12:32 CET

Desired situation
04-11-2015

**Comment by akvotender** [comment]
Created via Reamaze:

Link: https://akvoo.reamaze.com/admin/conversations/removal-of-automatic-time-zone-indication-with-calendar-questions
Assignee: Geert Soet

Message:
Dear support,

My partner Tiipaalga asked if there is a possibility to have the time indication removed when answering to a calendar-question.

Right now all the answers appear with the date + 0.00h UTC. Since they are dealing with a lot different date-questions and they have to do calculations with these different dates for different households (will eventually be more than 30.000 households) it takes them a lot of time to ‘clean' the data of this time indication.

So is it possible to have this disabled?
Thanks in advance,

Cheers,

Giel Hendriks
Chargé de Projet

T +226 76 94 80 00 (Burkina Faso)
T +316 47 69 97 74 (Pays-Bas)
E giel@akvo.org
T @GAHendriks
I  www.akvo.org
Akvo Fondation 
Afrique de l'Ouest

Latest Akvo Articles
- Simple is not easy. The new Akvo FLOW app. &lt;http://akvo.org/blog/simple-is-not-easy-the-new-akvo-flow-app/?pk_campaign=Simple%20FLOW&gt;
- Akvo Team Week 2015 – my wrap &lt;http://akvo.org/blog/akvo-team-week-2015-my-wrap-up/?pk_campaign=TW15%20wrap&gt;
- PIND Foundation, Nigeria – improves development co-operation &lt;http://akvo.org/blog/pind-foundation-nigeria-improves-development-co-operation/?pk_campaign=PIND%20Nigeria&gt;

**Comment by akvotender** [comment]
Created via Reamaze:

Link: https://akvoo.reamaze.com/admin/conversations/date-and-time-indication-issue-with-flow
Assignee: Geert Soet

Message:
Dear support,

My partner Tiipaalga asks if there is a way of ‘deactivating’ the time indication like 
&quot;UTZ +1” etc. 

They have several date-questions in their surveys. And when analysing/calculating their data the time indication is in the date-questions is unnecessary. For them apparently it’s quite an effort to delete this indication. 

Is there a way to deactivate this time-indication for them? 
It only concerns the date-questions. So that means the automatically generated date with every form filled in can be left untouched.

Thanks for your time,
Yours sincerely,

Giel Hendriks
Project Officer 

T +226 76 94 80 00 (Burkina Faso)
T +316 47 69 97 74 (the Netherlands)
E giel@akvo.org
T @GAHendriks
I  www.akvo.org 
Akvo Foundation 
West-Africa

Latest Akvo Articles

A Successful Camp: Open Data, Governance, Digital India and Caddisfly &lt;http://akvo.org/blog/a-successful-camp-open-data-governance-digital-india-and-caddisfly/?pk_campaign=ODcamp%20success&gt;
Notes from the Open Data Development Fair 2015, the Netherlands &lt;http://akvo.org/blog/notes-from-the-open-data-development-fair-2015-the-netherlands/?pk_campaign=Open%20data%20dev%20fair%20NDL&gt;
Investigating Akvo FLOW support &lt;http://akvo.org/blog/from-support-to-opportunities/?pk_campaign=support&gt;

We’ve won three awards this quarter:

Waterinnovatieprijs 2015 uitgereikt &lt;https://www.uvw.nl/?p=16942&amp;pk_campaign=Dutch%20water%20innovation%20prize&gt; 
Water and sanitation innovation in Latin America &lt;http://akvo.org/blog/award-for-innovation-in-water-and-sanitation-in-latin-america/?pk_campaign=LatAm%20WASH%20innovation%20award&gt;
Best video of World Water Week 2015 &lt;http://www.worldwaterweek.org/mywwweek/?pk_campaign=WWW%20video&gt;

**Comment by Geerts** [comment]
Hi guys,

Shall we try to get this one in the next release?

Thanks,
Geert

**Comment by ichinaski** [comment]
Issue will be addressed at https://github.com/akvo/akvo-flow/issues/257
