### ISSUE TITLE
Add JSX transpiler to dashboard build process (estimated: 1)

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1502]
As part of the introduction of react components in the dashboard, we need to be able to compile [JSX](https://facebook.github.io/jsx/) to JS code that will be embedded in different parts of the ember dashboard code. This requires including JSX transpiler tools in our current build process.

Child of #2796

**Comment by kymni** [comment]
Issue with survey/form filter. Investigating

**Comment by janagombitova** [comment]
With today's testing I found the following issues: 
* [ ] previewing different cascades acts out and does not load properly. But this only happens when I try to view the cascade 'France' so there might be something isolated going on. Not sure. 

<img width="1263" alt="Screen Shot 2019-03-13 at 15 42 56" src="https://user-images.githubusercontent.com/12456965/54288197-5639e300-45a7-11e9-90cc-cd2a6de70137.png">

**Comment by janagombitova** [comment]
I hope this is the last issue to be found: 
* [ ] answers to repeated groups do not show in the Inspect or Monitoring tabs. The repetitions show but the answers are blank. In Maps all works fine. 

![Screen Shot 2019-03-14 at 16 06 09](https://user-images.githubusercontent.com/12456965/54367798-47206700-4673-11e9-8061-a1436f728d60.png)

**Comment by kymni** [comment]
@janagombitova seems the reason this particular response does not display is because the question is type option but the values submitted are free text (maybe was initially text then changed type after submitting?). Flow therefore tries to look for text property in the response but not finding it returns null hence the blank. Issue is therefore not webpack related but we still need to catch such cases

**Comment by janagombitova** [comment]
@kymni that you for checking. Thas it very odd. I will try to reproduce it on a production instance and create a separate issue. Then all webpack issues should be handled. I did not find anything more.

**Comment by valllllll2000** [comment]
everything works as expected
