### ISSUE TITLE
Tasks are unnecessarily rerun for every form response submitted

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1594]
When uploading form responses through the raw data reports from FLOW services, we are rerunning certain tasks that are processing data points not necessarily connected to or affected by the form responses that are being uploaded.  We need to investigate the task path when uploading these reports to eliminate unnecessary reads and writes from the datastore.

**Comment by muloem** [comment]
### Test Plan 

1. Create a sample (monitoring) survey, fill in some data in the registration form and then export the latest raw data report of this form

2. Edit the report and update some of the responses

3. In addition add some new responses i.e.without the instance id, identifier etc

4. Upload the report and cross check on the monitoring tab that the **only** data points whose registration forms were updated have changed dates in the *Last Updated* column.  Also check that new data points were created correctly and their *Last Updated* date is correct

**Comment by rumca** [comment]
test plan passes as described

**Comment by rumca** [comment]
Actually re-opening this. The above test plan passes, however I've just noticed some weird behaviour which after discussion with @ichinaski is potentially related to the above changes.

I think question summaries are not being rebuilt correctly when you upload cleaned data. Charts on the ``REPORTS > CHARTS`` tab look correct when you submit data from a device. However when I then download a report, make some changes, and reupload the cleaned data - the charts are no longer correct. Instead of showing a chart of multiple responses, they simply just show the latest response (not the cleaned data behind showing how many responses there actually are).

![screen shot 2016-04-20 at 12 45 17](https://cloud.githubusercontent.com/assets/3003031/14673427/d0242be2-06f5-11e6-93d8-00e3db000ec1.png)

**Comment by rumca** [comment]
redeploying FLOW services with latest release candidate fixed this issue
