### ISSUE TITLE
Serving static files from the backend - estimated: 6

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1688]
In a number of cases, we have images and some JS library files that do not change frequently.  As a way to improve the performance of app loading, we should modify the deployment to take into account some of these files and take advantage of the current (and possibly future) platform's capabilities around serving static files.

Where possible  we can serve the JS libraries from an existing CDN.

**Comment by janagombitova** [comment]
**From planning poker meeting:** This issue means identifying the files. Questions as If you have changed the file how do you keep track of it and how to test this? came up in the discussion

**Comment by kymni** [comment]
## Test plan
* Open browser's console to inspect loaded libraries
* Confirm that the following libraries now load from CDNs instead of from Flow
  * jQuery
  * jQuery-UI
  * handlebars.js
  * ember
  * jQuery.dataTables
  * d3
  * resumable
  * mapbox/cartodb
  * iframeResizer
* Same applies for public interface

**Comment by janagombitova** [comment]
@stellanl could you check  this fix on uat1 for me? (so we get an unbiased test run)

**Comment by stellanl** [comment]
Admin: check.
Public: check.
