### ISSUE TITLE
Style sheet overlay causing un-clickable dropdown 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1703]
In the Monitoring tab, when navigating the folder/survey/form dropdowns at one level the dropdown 'Choose a folder or survey' is un-clickable. After some investigation we realised that it depends on the size of the browser screen or where precisely the user clicks. Emmanuel found out that in the style sheet there is a layer that is disabled but falls sometimes over this dropdown causing it not to work as expected. 

![css issue monitoring](https://cloud.githubusercontent.com/assets/12456965/15892985/48fb4c0a-2d7d-11e6-988e-22c84d4116ac.gif)

**Comment by gabemart** [comment]
Yep, the problem is that the container for these menus is set to display at 48% width, and there is another (empty) container in the same row set to 50% width. When the contents of the first container overflow, they are positioned under the empty container and are unclickable.

To fix, we can:

* set the width of the first container to 100% so it always fills the row
* remove the second (empty) container - it is always empty so serves no purpose

**Comment by gabemart** [comment]
### Test plan

1) Open the data monitoring tab
2) Open a folder with at least one survey nested at least 3 levels deep, i.e. there are at least 4 dropdown menus visible, like so:
![image](https://cloud.githubusercontent.com/assets/2589977/16489581/1aec87ea-3ece-11e6-8aed-cdd46447ae0d.png)
3) Adjust the browser window size so that the viewport is around 1100px wide
4) Verify that all areas of the last dropdown menu are clickable

**Comment by janagombitova** [comment]
👍 test plan passed

**Comment by janagombitova** [comment]
👍 fix passes regression test as well
