### ISSUE TITLE
Cartodb custom maps - colour up the points on map as user makes styling changes

### ISSUE THREAD

**Issue by kymni** [akvo/akvo-flow#1705]

**Comment by janagombitova** [comment]
#### Issue Background 
With this new feature the user will be able to create a map with data points that are colour coded based on a category (answer to an option question in a form). Flow will give the users a initial colour palette per each option and the user can customise the colours as they wish. 

@kymni has implemented a colour picker that provides the palettes (currently only supported by certain browsers) 

This issue was created because after the 1st round of testing we learned that the colouring only happened after the user hit Save on the map. The points were not coloured based on the colours given to the separate options right away. Secondly, after trying to change the colour in the colour picker and the same happened as well, the colour field next to the option question changed right away, the but point colour changed only after hitting save.

#### Current status 
After trying a few test cases this issue seems to be fixed. Points are coloured right away and also reflect the new colour after the user changes it. 

#### Open issues 
In the user testing one of the observation we made that most of the user did not intuitively figure out that they can change the colour that were given to the options. After navigating them to this customization they were very pleased about the possibility.  
@loicsans and @Kiarii When looking into improving the front end design of the maps with @kymni can you please take a look at this issue as well?

**Comment by janagombitova** [comment]
Following the decisions shared here akvo/akvo-product-design#143 (comment) I am closing this issue as the functionality of Custom maps will not be part of Flow's feature list.
