### ISSUE TITLE
Photos cannot be updated via datacleaning

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-flow#1733]
As part of #1527 , the updating of questionType Photo was prohibited.
This however broke some backward compatibility usecases which are being used by current partners.

Usecase:
1. In most big scale projects, all the data from the field is not collected under a single survey. There are multiple reasons for it like
           a) Since we cannot create datafilters in the dashboard based on responses, so it becomes difficult for partners to look at specific data
           b) In some cases there are reasons why a partner from one province should not be able to look at data from the same project from another province
 In these cases the central office collects the cleaned data from the provinces and adds them against a master survey so that they can generated reports for the overall state of the project
Ex: Aga khan foundation, East meets west etc
2. In some cases, partners keep a copy of the "original data" before any dashboard cleaning happens. This helps them to gauge the quality of data coming in from the field and provide feedback. Ex: Cardno
3. In most resource based financing project where subsidies are used as motivation for distribution of assets, a regular workflow is executed are regular intervals.
These are then merged together in one master upon which a program tasks such as reports and approvals are executed. Ex: SNV

In any of the above cases, loss of field data because of merging is not acceptable for the partners.

**Comment by joycarpediem** [comment]
After discussion with @janagombitova , we have decided to re-enable uploading of photographs via data cleaning.
The geotagging of these photographs will be ignored. The geotagging column is currently not available for cleaning and will stay that way.

**Comment by janagombitova** [comment]
**No test plan but the fix works:** 
- when uploading new data via data cleaning that hold a photo link (previously captured in Flow and copied into this new data set) the photo is properly uploaded and clickable 
- if the uploaded photo previously showed a geotag, the location information after data upload is not provided anymore 
- with data cleaning of existing data - instead of link A copying in link B - the photo is changed as expected 

👍  can be considered fixed and tested
