### ISSUE TITLE
Display name does not get updated for large surveys

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-flow#1743]
Steps:
1. You need a forms with >5000 records
2. Change some of the questions that are marked as "Use as data point name" and publish

Issue:
Only a small percentage of Display names get updated.

Possible cause:
The GAE task times out before all the records can be updated.

**Comment by Nikki-Akvo** [comment]
another potential case here; https://akvoo.reamaze.com/admin/conversations/questions-on-akvo-flow

Smaller survey (208 point), and names are updating on their own after some time.

**Comment by Nikki-Akvo** [comment]
Additional case; https://akvoo.reamaze.com/admin/conversations/5d1d2bb6438948f4

Mars Food, 5 data point names missing as of 30/09/2016

**Comment by Nikki-Akvo** [comment]
Additional Case: https://flowhelp.reamaze.com/admin/conversations/missing-data-point-names for the Welthunger dashboard.

**Comment by stellanl** [comment]
My guess is that the update of the (SurveyInstance) entities shown in the raw data report used to happen through the app, because there was no code in the backend to update it until #2160. So if the app could not send more than 5000 items that would also explain it. And the app subsequently changed so it only sent this data for registration forms.

**Comment by janagombitova** [comment]
Will test this one after the 1.9.21 release to confirm if it is still a problem or not

**Comment by janagombitova** [comment]
I have cross checked the data point update in exports of a few surveys from Libera with over 20k submissions and all worked as expected. 

Closing this issue and if we hear of a specific case we can reopen it again
