### ISSUE TITLE
Export crashes w NPE if cascade question has no cascade

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#1795]
If a CascadeQuestion has no assigned cascade at the time of a data export this is not handled for the data cells, and an NPE is thrown at GraphicalSummaryExporter.writeAnswer(L691).

This case is already handled for the _header_, by not showing a column at all.
A more elaborate fix would be to put a "missing cascade" string in the cell instead.
Question is which is most helpful for the user.

**Comment by janagombitova** [comment]
@stellanl can you please add a test plan here? Thank you

**Comment by stellanl** [comment]
Test plan:
Submit a data point for a survey with a valid cascade question.
Select no cascade resource for the question.
Request a report for the survey. 
The report should be successfully generated, but with no column for the cascade question

**Comment by janagombitova** [comment]
Could not test exactly by this plan because if we want to save a cascade question without the added resource the validation does not allow it, but copied a survey with cascade from a different dashboard and managed to test the reports if the cascade resource is not selected. 

The behaviour is as expected: the cascade column shows no answers and all reports generate without trouble. Reports where cascade is selected also generate without problems 👍  well done!
