### ISSUE TITLE
Caddisfly resource file triplicated

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1825]
The `caddisfly-tests.json` file has to be shared in the app, GAE backend and Flow services deployment in order to share the test information across. This creates the risk of the file going out of sync when changes are made to the test definitions.  In addition it creates a dependency of caddisfly tests development on the Flow release cycle.

In order to minimise the dependency of caddisfly on Flow release cycles as well as to avoid errors with outdated files, we decided to load caddisfly test definitions from a CDN.  These test definitions can be updated by the caddisfly team whenever they need to update them without any interference from the Flow team.  In case the definitions file is faulty, Flow informs that user that the caddisfly tests file could not be loaded.

**Comment by janagombitova** [comment]
In the first round of testing I cannot load in the test file due to missing https connection. 

<img width="1277" alt="screen shot 2017-09-06 at 16 19 26" src="https://user-images.githubusercontent.com/12456965/30117123-a0f5e344-931f-11e7-8b53-3bf2bdf46de9.png">

Thus in the survey editor I cannot create new surveys forms with Caddisfly questions or preview existing forms with Caddisfly questions. 

The good this is (as we wanted) that if the file is incorrect Flow will not break and keep on working, showing an error to the user. 
@muloem can you please change the error text form the current: “Failed to load caddisfly tests!” to `Failed to load Akvo Caddisfly tests`

I on the other hand can see already submitted data, export the data. I can also get existing forms to my device, see previously submitted data correctly and submit new data. Exports work fine as well in this round of testing

**Comment by janagombitova** [comment]
Survey forms that already had Caddisfly questions show properly in the editor, new forms with new questions with Caddisfly tests show properly and save properly in the editor. On the app the user can work with, see, submit data for existing and new forms with Caddisfly question. Viewing data in Inspect data tab, Monitoring and both maps also works as expected 👍 

Waiting to test exports

**Comment by janagombitova** [comment]
Data exports (of all kinds) work well as well as data cleaning. The user cannot clean Caddisfly data as expected and the columns and variables are properly generated in separate columns. 👍  Well done
