### ISSUE TITLE
Modified date in survey overview does not update

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1838]
When looking at the list of surveys the users gets two date indications, of the date when the survey was **created** (not changeable) and of the date when the survey was **modified** (should change with the survey). However the **modified** date does not update after changing the survey, with or without publishing. 

![modified date](https://cloud.githubusercontent.com/assets/12456965/20554349/a6b320f4-b15b-11e6-8b3e-23422daf32e9.gif)

**Comment by kymni** [comment]
It appears the survey group update endpoint only triggers when the survey group basics (Survey title, privacy type, etc) are modified. Potential fix is to set the survey group's "lastUpdateDateTime" property with the latest timestamp each time a survey update is triggered

**Comment by janagombitova** [comment]
I agree. The modified date should change when any change is made to the survey or one of the forms in the survey, so covering actions as: 
- change to survey name
- change to survey privacy 
- change to monitoring enabled 
- change to data approval enabled 
- change to form name 
- change to form translation
- change to question group 
- change to any question

**Comment by kymni** [comment]
The "lastUpdateDateTime" property of both the surveys and survey_groups endpoint  is system generated. We can therefore take advantage of this by setting the property to empty before committing to trigger the update.

**Comment by muloem** [comment]
@janagombitova @kymni So we currently have a solution for this issue where we show the latest modified date of a survey, however, the consequence is that we have two extra calls to the backend for saving a question (save a survey and save the associated form).  I am not sure how this behaves on a slower connection and whether or not it will disrupt things a little so before we look into that I have a bit of devil's-advocate type question.  Do we _really_ need to have the modified date time on a survey?  What do the users really use it for?  And can we address that _what_ in another way?  We've made some good progress on improving performance so I would like us to be sure that if we add something that may degrade it, there is a strong argument why and no other alternatives.

**Comment by janagombitova** [comment]
@muloem I agree that any changes we made cannot compromise performance, we should aim to always speed things up. So if the fix is slowing things down, then we should reconsider the approach. 

What is the value of the modified date: 

From user feedback we know that there are more people involved in survey design. There is Petra with more Petra-s looking at the overall goals of the programme and what data do they need to understand the situation. She creates the survey. But there is also Salim and other Salim-s who work with her to make sure the survey fit local context, put them in Flow, test them out. Sometimes Petra creates the 1st version of the survey and then Salim goes in and makes some changes. But Petra has no way to know currently. Only via version number (which can be hard to remember and does not change if the survey was not published) or by the modified date, which is easier to keep in mind.

The modified date then is seen as a way to keep an eye on the changes to the survey forms. So if we want to tackle the full problem here, we should have a way for people to see who changed what on the survey form and when. I feel that is something of a larger scope and for the future once we get to the survey editor improvements

**Comment by kymni** [comment]
Regarding the performance hit, the two extra calls we're getting are because the fix is triggering change of the `lastUpdateDateTime` property for both survey (form) and survey group (survey). The actual setting of the property value is done in the back-end. What we could therefore do is have the question and question groups update end-point also modify the `lastUpdateDateTime` properties for the survey and survey group. This would have no effect on the front-end as all action would take place on the back-end.

**Comment by muloem** [comment]
What you are talking about is something along the lines of a http `PATCH` request.  I am in favour of that since it will not incur more cost in terms of number of requests.  The only difficulty I see is that if we make any updates to the UI, any commits will automatically make the individual requests.  We can check whether in the later versions the `bulkCommit` enables sending multiple entities in one request.  

Another thought is that we have two save buttons.. one for the survey and one for each of the questions.  We could consider having a single save button at the survey level or no save button completely and have an autosave.  This way changes will update the survey and only update the targeted specific question. 

Finally, if we are able to _drastically_ bring down the request times, we could indeed allow multiple calls.
