### ISSUE TITLE
Unify Users's tab design with new table design

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1999]
Users tab is not aligned with the new table colours. This is for both users list and roles and permissions
 
<img width="1040" alt="screen shot 2017-03-03 at 17 03 22" src="https://cloud.githubusercontent.com/assets/12456965/23558403/bd15d914-0033-11e7-9109-008fabde96c4.png">
<img width="1048" alt="screen shot 2017-03-03 at 17 03 31" src="https://cloud.githubusercontent.com/assets/12456965/23558405/be76401e-0033-11e7-9807-2f5a7621c660.png">

**Comment by loicsans** [comment]
This is a tricky one, I have made the required changes but have no idea why this is not reflecting on the UI. The issue is that this tab is loaded within an iframe, runs on clojure script and has its own css stylesheet. I had discussed this issue with @jonase and asked some insight but then we have not had time to follow up quite yet.
