### ISSUE TITLE
Simplify assignment modal dialogue - deleting

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2119]
<img width="694" alt="screen shot 2017-06-06 at 13 42 40" src="https://cloud.githubusercontent.com/assets/12456965/26827570/38b812a6-4abe-11e7-885c-d2bb5d83d5c7.png">

Current modal dialogue that shows after a user wants to delete an assignment can be improved and simplified. The buttons need to relate directly to the actions. The outcome of the users decision needs to be clearly stated. 

## Suggestions 

Change text to: "Delete assignment" 
Buttons: instead of OK > "Delete" ; leave Cancel as it is 
Colours: Keep only the white background. No need fro the grey area around the text field. 

Do we need to explain that "this cannot be undone" or is that clear from the delete action itself. I personally am in favour of removing this sentence, but would like to hear your thoughts.

**Comment by Maseline** [comment]
I think it's nice to have a warning statement if the information being deleted is crucial

**Comment by janagombitova** [comment]
Hi @Maseline after consulting with the design team a while ago we agreed that keeping the dialogue as simple as possible is the best way to go. So the expectation is to have: 
- Delete assignment? 
- buttons: Delete and Cancel

**Comment by janagombitova** [comment]
Hi @Maseline the final change is: 
- Title: Delete assignment? 
- Buttons: Delete, Cancel 
- remove the text and background colour (grey) 
- Delete button has the same design as the current OK button 
- Cancel button has the same design as now

**Comment by Maseline** [comment]
@janagombitova , one more commit and all changes are complete, however, wanted to let you know that changing the button text to Delete, that change is applied across all similar dialog boxes, meaning any other delete option that opened a dialog box now has delete and cancel as the button options, this is because of the way the dialog box was set up in general. Is this okay?

**Comment by janagombitova** [comment]
@Maseline if you can cross check and confirm that it only affects the Delete dialogues, then it is actually perfect! Please add a note later to the test plan to cross check once more that only delete dialogues have the button change

**Comment by Maseline** [comment]
Test plan
Select Devices from the navigation bar
Under devices select the Assignments list
Select the option to delete one of the assignments in the list, if none exists, create a new assignment and try deleting it.
The new dialog box should have Delete Assignment? as the heading, no warning message and the buttons should have the text Delete, Cancel

**Comment by Maseline** [comment]
@janagombitova @muloem As i'd shared up there that changing the ok to delete could potentially affect other dialog boxes, i just found one, under the Data tab -> Data Cleaning,  options Raw Data Report and Import clean data open dialog boxes as well, now showing Delete instead of Ok,
Looking into this now

**Comment by muloem** [comment]
We can close this one since the proposed solution affects more areas of the UI and we need do not want to get into that much reworking right now.
