### ISSUE TITLE
Maps code refactor

### ISSUE THREAD

**Issue by kymni** [akvo/akvo-flow#2144]
The current code that controls the maps needs to be refactored to align it with the rest of the framework. This means that parts of the code such as calls for survey groups, surveys, questions, and answers which are currently being made need to be replaced with standardized and reusable versions used in other parts of the dashboard

**Comment by kymni** [comment]
Creating new branch to better structure the changes

**Comment by kymni** [comment]
## Test plan
* Mapbox maps function as before
* Changes in Cartodb maps
  * Folder/Survey filters now load in same style and manner as rest of dashboard
  * Survey groups end point no longer triggers each time you open the maps tab
  * Answers endpoint now pulls responses from Flow storage instead of Carto

**Comment by janagombitova** [comment]
Here are a few issues from the 1st test round: 

## 1) Loading spinner kept on spinning
![screen shot 2017-10-31 at 10 13 14](https://user-images.githubusercontent.com/12456965/32218229-918b2140-be2a-11e7-955d-2e196fc66599.png)

## 2) Sometimes data points did not render
![screen shot 2017-10-31 at 10 56 44](https://user-images.githubusercontent.com/12456965/32218246-9e8604fa-be2a-11e7-90a3-468ab0aa2ee4.png)

But once I reloaded the entire instance maps showed to points for the same selected form 

## 3) Forms remain on map also after selecting a new folder 
I selected a folder > survey > form and then the points loaded on the map. Then I selected another folder, but the initial points remained on the map until the point I selected the new form. I would expect that once I select a different survey or folder, that the points will disappear from the map

## 4) Missing data point name, Submitter 
When opening a point I only see Collected on. Previously we also showed the data point name, ID (I think) and submitter besides the questions and answers. These should be brought back

**Comment by kymni** [comment]
Unable to replicate issues 1 & 2

> 3) Forms remain on map also after selecting a new folder 

We've reused the folder/survey selectors used in other parts of the dashboard so unable to bind the event listeners, which would allow us to clear the map as selection changes

> 4) Missing data point name, Submitter

The refactor reuses the end point that pulls point data from Flow instead of Cartodb. This end point does not currently provide these two properties. We've therefore replicated the details as displayed on Mapbox maps

**Comment by janagombitova** [comment]
> 1) Loading spinner kept on spinning
> 2) Sometimes data points did not render

Could not reproduce either. Will test out more later to see if I can get it happen again.

> 3. Forms remain on map also after selecting a new folder
We've reused the folder/survey selectors used in other parts of the dashboard so unable to bind the event listeners, which would allow us to clear the map as selection changes

Is there a way to make sure that once I select a different survey or folder that the points are removed from the map? The current implementation is confusing and not giving the best experience as the user selects a different survey and if this one perhaps does not have any points to it, she still sees the previous points on the map. 

> 4. Missing data point name, Submitter
The refactor reuses the end point that pulls point data from Flow instead of Cartodb. This end point does not currently provide these two properties. We've therefore replicated the details as displayed on Mapbox maps

The value of the Carto maps in comparison to the mapbox one was that it was not only more up to date; faster and accurate, but also that it showed these important details that help our users identify the data points. So we need to find a way to bring this info back, also for the future Windshaft maps.

**Comment by kymni** [comment]
**Issue 3** should be resolved now. **Issue 4** can be fixed by modifying the end point which falls under a bigger refactor

**Comment by kymni** [comment]
**Issue 4** should be resolved now

**Comment by janagombitova** [comment]
Hey @kymni and @muloem after another test round I have these comments: 

## 0) on previous 3) Forms remain on map.. 
This is indeed resolved and much better. Thank you. 

## 1) On previous 4) comment of data point details missing

Can you please match the UI with the current carto implementation as that one follows the work you did with Kiarii previously? 

![screen shot 2017-11-15 at 10 02 20](https://user-images.githubusercontent.com/12456965/32827350-2718d384-c9ec-11e7-8aaf-a65776cdfb62.png)

## 2) Loading spinner spinning when looking at data
Managed to get another error that resulted in the loading spinner going on and on. This happened once I selected my survey and form (1. Amsterdam Bikes > Bike registration Form) and then clicked on a point to see the captured data. 

<img width="1244" alt="screen shot 2017-11-15 at 09 59 43" src="https://user-images.githubusercontent.com/12456965/32827404-6168f136-c9ec-11e7-9a97-1ba9959195bd.png">

## 3) Missing map tiles in side bar for geoshapes
When there is a geoshape question we have the little map in the side bar where we show the shape and then the user can decide to show it on the main map. Showing and hiding on the main map works fine, but I cannot see the geoshape in the side bar and neither the map tiles. 

<img width="1243" alt="screen shot 2017-11-15 at 10 08 06" src="https://user-images.githubusercontent.com/12456965/32827651-336004d6-c9ed-11e7-8d68-ac86b7392b10.png">

**Comment by janagombitova** [comment]
@kymni 

## 1) UI 
Let's talk about this one 

## 2) Loading spinner spinning when looking at data
Resolved 

## 3) Missing map tiles in side bar for geoshapes
I see the map now and the shape, so that is resolved. But it looks quite funky: 

<img width="1241" alt="screen shot 2017-11-15 at 11 19 54" src="https://user-images.githubusercontent.com/12456965/32830949-15eb3006-c9f7-11e7-8f15-f34fa77dc6ba.png">

**Comment by kymni** [comment]
> I prefer the changes you made on the data point details. But now the photo is also showing before the questions and that is not needed as it is rendered later on with the question. Showing the photo on the top is how we do it in the "old" mapbox maps.

For issue 1 we'll do away with the old way of displaying the images at the top and keep the new way which is displaying the image on the responses section of the details panel
> I see the map now and the shape, so that is resolved. But it looks quite funky:

This will be tackled under #2320

**Comment by janagombitova** [comment]
From a last flowaglimmerofhope check: 
1) resolved
2) resolved
3) resolved as well as the funky-ness

**Comment by janagombitova** [comment]
All seems to be working fine and as expected. I think we are ready to roll and can tackle issues (if any) separately in smaller fixes. Well done 👍
