### ISSUE TITLE
NPE in SurveyInstanceServlet.makeDatapointName

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2211]
A little optimism made it into #2060.
At org.waterforpeople.mapping.app.web.SurveyInstanceServlet.makeDatapointName. L 130-131 we assume that the surveyInstance has a non-null surveyedLocaleId. But a few don't. So we should protect against that.

**Comment by janagombitova** [comment]
@stellanl Can you add a test plan please? Thank you

**Comment by stellanl** [comment]
This one is hard to test without making a deliberate error in the data store. The log entries that I looked at to diagnose this are all gone by now, and I don't remember which instance had this problem with reports.

**Comment by stellanl** [comment]
Make a report on UAT1, form 185699118, if fix was successful, it should work but one datapoint name should be blank.

**Comment by janagombitova** [comment]
@stellanl the export works, but all the display names are not generated anymore

**Comment by janagombitova** [comment]
@stellanl I have tried to confirm your assumption that we get only data point names for monitored surveys. Here is what I found: 
Old survey forms: 
- monitored (registration and monitoring forms) all work ok, with point names 
- monitored with one form only and then changes to non monitored - also ok
- non monitored - also ok (see raw data report attached)
Newly created survey forms (since the UAT build) 
- monitored (registration and monitoring forms) - all ok
- non monitored (the one you made changes to in the data store) - **no data point names**
- non monitored (no changes in the data store made to it) - **no data point names**

**Comment by stellanl** [comment]
Ok, makes sense since the new code ignores the stored value (since it was expensive and complicated to keep it updated when the defining questions changed) and builds it from the current questions and answers while exporting. Apparently non-monitored surveys do not set the creatingSurveyId of their surveyedLocations entities.

**Comment by janagombitova** [comment]
👍  Yay works now
