### ISSUE TITLE
Comprehensive export file - Excel error message 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2279]
After requesting a comprehensive export for the first time and opening up, you get an error message from Excel that the content is unreadable and asking if you want to Open and Repair. After Open and repairing the file works ok but this message can be scary to users. 

I have attached the xml file Excel saved with the changes made. Can be found here: https://drive.google.com/open?id=0B4BNcLtl6pHrRWRiTUdqQjdGejQ

<img width="486" alt="screen shot 2017-10-17 at 14 14 24" src="https://user-images.githubusercontent.com/12456965/31664415-99f63c38-b345-11e7-8166-2101918fb885.png">

The Excel I run is version 14.7.1

**Comment by janagombitova** [comment]
Created via Reamaze:

Link: https://flowhelp.reamaze.com/admin/conversations/akvoflow-support-request-number-77444-from-lissy-at-akvo-dot-org

**Comment by stellanl** [comment]
Checking against some clients:
 * LibreOffice 5 gives no warnings.

**Comment by stellanl** [comment]
Since it is just the comprehensive report, my guess is it's due to the pie charts. Will test this.

**Comment by stellanl** [comment]
Test plan: Since we no longer output frequency table for number questions, the only way to test it properly is to generate an option question with 100 options, and then answer it 100 different ways.
The resulting comprehensive report should not make Excel unhappy.
(Or we might wait until we add statistics for cascade questions, for which such data already exists.)

**Comment by janagombitova** [comment]
Report works and all looks as it should, with the pie charts not showing for number questions.
