### ISSUE TITLE
In Monitoring tab remove navigation arrows when viewing details for data point

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2389]
# Context

When in the Monitoring tab you select survey form and then a data point point from the list. In a pop up window you see all the forms submitted to the data point and you can click on a submission to view the details. 

In the UI in the table header in this pop up window, all columns have navigation arrows that indicate you could possible sort your table. There do not work and thus only clutter the screen. 

<img width="1064" alt="screen shot 2017-12-13 at 11 32 19" src="https://user-images.githubusercontent.com/12456965/33934644-d166f50a-dff9-11e7-93af-2bcf2b9a0085.png">

# Changes 
Before we make larger UI changes on how one views data, let's simplify what we have currently and remove all these arrows from the submission list in the pop up and also form the submission view when looking at answers.

**Comment by bogere** [comment]
After investigating the issue, I realized that navigation arrows(sort-able arrows) in the table are actually background images  in the data table class. Also sorting capability only works in the messages table but not the inspect and  monitoring table..
### solutions proposed 
*  make the inspect data and monitoring  tab  table sortable like the messages table.
 this would be the most viable option.
* Make a seperate table class for the monitoring and inspect data tab so that they do not use default data table class . But that  would bring alot of changes especially in the styling part.
```
thead tr {
        background: rgba($linkColor, 0.2);
        border-top: thin solid rgba(32, 32, 36, 0.05);
        th {
            position: relative;
            padding: 9px 1em 9px 1em;
            border-right: thin solid white;
            background: url(../images/sortTableArrows.png) right center no-repeat;
            text-align: center;
            font-weight: normal;`
```
After having a talk with Jana, we decided not to resolve it for  now because there is also  too much dependency on the data table  css class and also there issues that are more urgent than this one..
@muloem  and @kymni  what do you think about this issue before we can close it

**Comment by kymni** [comment]
@bogere given that the issue definition is about hiding the sort arrows, we can look at modifying the styling so that the arrows simply don't show on the monitoring and inspect data table headers

**Comment by bogere** [comment]
@kymni yes that would work for only the inspect data and monitoring table headers but would affect the appearance on the messages table since styling for data table is general

**Comment by muloem** [comment]
Since there are bigger changes internally to enable sorting I would also be in favour of removing the arrows for now and we can pick up the sorting in a different issue.

**Comment by kymni** [comment]
We have an unused `noArrows` class so it's just a matter of modifying to make it available to the relevant tables https://github.com/akvo/akvo-flow/blob/1f07c7d9fd4f009be390227f2739d71d4eb2f5c9/Dashboard/app/css/main.scss#L3299-L3303

**Comment by kymni** [comment]
## Test plan
* Open inspect data and monitoring tabs
* Confirm sort arrow no longer there

**Comment by valllllll2000** [comment]
Works prefectly
