### ISSUE TITLE
Comprehensive report: Display table and graph for cascade answers

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2427]
Since cascades are used much the same as options we should show the frequency table and graphs for them, too.

**Comment by janagombitova** [comment]
Tested today and it looks good, but the current implementation takes all the cascade levels into the graph. It should only take the last level (the leaf). Spoke with @stellanl and he said that was the intention, but due to inheritance from multiple-options code this situation of taking all levels is a bug. 

Needs to be fixed for the release

**Comment by janagombitova** [comment]
👍  works like a charm and I hope our users will find it helpful too. There are small improvements we can make like adding the percentages to the charts, but let's leave that for another improvement round. This can be considered done.
