### ISSUE TITLE
Simplify Messages - stop logging form submission in the UI

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2496]
# Context 

We aim to **simplify** Flow and to keep the user as informed as possible, but not over-informed or confused. Currently the Messages tab holds a lot of important information and status updates that we are working on improving and brining closer to the actual action. It also holds information updates that are not useful at all and clog the list. 

More details are here: https://github.com/akvo/akvo-product-design/issues/285

# Opportunity 

With this issue we would like to remove logging in the UI the message shown with each form submission made from the app to Flow. Every time a user submits a form that is fully synced in, we show a line in the Messages tab with the **fileProcessed** message. 

![screen shot 2018-02-19 at 13 38 07](https://user-images.githubusercontent.com/12456965/36378836-c96fedf8-157c-11e8-9788-9465c5b0a1b4.png)

Users go to the Inspect data tab or to Exports to see if the submissions are in properly and find this update in the messages tab useless.

**Comment by janagombitova** [comment]
We log submissions in Messages tab for submissions that are synced in online but also for those imported with bulk upload. In the case of bulk upload we show the bulk upload success message and also the submissions. 

<img width="1197" alt="screen shot 2018-04-17 at 13 00 03" src="https://user-images.githubusercontent.com/12456965/38869488-22adc516-424b-11e8-9b86-019c9457b62f.png">

With the changes here #2471 we give Salim direct feedback about the success or failure of bulk upload directly in the page. So with this issue we can completely stop logging in the UI submission related messages and bulk upload. 

@kymni you has some concerns around logging down the events? Can you share them here?

**Comment by kymni** [comment]
The current implementation such as a published survey, instance submission, report export, etc. across the dashboard are all logged into the messages data store. The messages end-point therefore simply returns the last 20 events logged. We can filter out what's displayed to the user on the client-side by simply applying some rules on the `actionAbout` property. This would however not solve the issue because the end-point will still have returned unnecessary info. We therefore need to either stop logging some of these events altogether or apply the rules on the server-side so that only the last 20 relevant messages are returned
