### ISSUE TITLE
Rename and reshuffle tabs 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2731]
Another round of simplifying our design on the online workspace. 

<img width="1233" alt="screen shot 2018-06-26 at 09 57 50" src="https://user-images.githubusercontent.com/12456965/41897354-63ae82fe-7927-11e8-9768-86b25cdb5e57.png">

# Export 
Some partners asked why do we call Export reports tab reports if you are not really exporting a report, more of a data dump and a survey form. The suggestion is to rename the subtab to **Exports** 

# Map
Considering the Maps tab provides another way to look at data that is submitted to Flow, how about we move it under the Data tab, after Monitoring? 

# Library/Resources 
The positioning of Cascade resources (and Data approval for the 2 instances) under the data tab has always brought questions on why they are there. These two hold resources that can be used across any and multiple surveys and forms. How about we create a new tab called Library or resources and have these two subtabs live there? 

What do you think @muloem @Kiarii @loicsans @stellanl @kymni @valllllll2000 ?

**Comment by Kiarii** [comment]
@janagombitova I recall we have had similar thoughts - on the exports, data view options (list, table, map) and library for global resources - while looking at other aspects of flow; I think these would be natural and logical improvements

**Comment by janagombitova** [comment]
Hi @Kiarii, yes indeed. This issue was my suggestion to get us another step closer to that vision on yours. 👍

**Comment by muloem** [comment]
> Some partners asked why do we call Export reports tab reports if you are not really exporting a report, more of a data dump and a survey form. The suggestion is to rename the subtab to Exports

This makes sense to me  👍 

> Considering the Maps tab provides another way to look at data that is submitted to Flow, how about we move it under the Data tab, after Monitoring

I would hold off on this one for a little bit longer.  Its true that Maps provides a way to look at data but I believe that is a kind of misuse of maps.  They are more a visualisation tool which in my view implies aggregated data rather then specific data points.  I believe we can rethink the way we support the viewing of data to make it more user friendly for the partners to achieve what they do with maps (and reports) under the inspect data tab.

> The positioning of Cascade resources (and Data approval for the 2 instances) under the data tab has always brought questions on why they are there. These two hold resources that can be used across any and multiple surveys and forms. How about we create a new tab called Library or resources and have these two subtabs live there? 

In this case the cascade one is clear to me although I have never really thought deeply of what it means to move data approval as well.  But its true that both are used across various surveys so that makes sense.

**Comment by kymni** [comment]
## Test Plan
* Load dashboard and confirm that a new tab labeled "Resources" now exists
* Click the tab and confirm that cascade resources are now found under the tab
* For data approval enabled dashboards, confirm that data approval is also under this tab
* Confirm that tab under Data tab that was previously labeled "Export reports" is now labeled "Exports"

**Comment by valllllll2000** [comment]
Works as expected!
