### ISSUE TITLE
Use google maps with the updated mapbox library

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#2864]
With the upgrade to a more recent mapbox library #2769, the instances on which google maps is enabled are broken.  If we need to switch to google maps in the short run, we need to fix the connection so that they are able to run with the latest mapbox libraries.

**Comment by janagombitova** [comment]
I personally do not think we need to support Google maps for the future. If I remember correctly we had to enable Google maps for a partner as the border lines for disputed areas were not in conform with the organisation they were working with at the time. Since then we did not receive any similar requests or issues.
