### ISSUE TITLE
Flow datastore exports

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#3161]

**Comment by dlebrero** [comment]
We finally opted for an external cronjob running in k8s that uses the service accounts of akvo-flow-server-config.

Code is at the Akvo-platforms repo. See https://github.com/akvo/akvo-platform/issues/172.

The cronjob is running but right now just backs up the data from akvoflow-dev2. This is so that we can monitor its behaviour for a couple of weeks before enabling it for all instances. 

The only other piece of work to be done is the check how long it takes the job to run once all the instances are enabled, as right now one instance backup is not stared until the previous backup finished, which we guess it can take a long time.

Making the backup async is easy (https://cloud.google.com/datastore/docs/export-import-entities#async-flag) but we are not sure what that will mean from an error reporting point of view.

**Comment by janagombitova** [comment]
@dlebrero thank you for the work and the update. Two follow up questions: 
* how often will we back up the data? 
* when do we aim to enable the cronjob to production?

**Comment by dlebrero** [comment]
Once a week, due to the $$$ cost, which I think Emmanuel has already talked about with you.
In a couple of weeks, once it has run a couple of times and Emmanuel and Oriol have review the code.
I will run a one off backup for all instances today (hopefully)

**Comment by dlebrero** [comment]
Backed up all instances.

Found two issues, that I will let the Flow team handle: 

1. https://github.com/akvo/akvo-flow/issues/3169, which I fixed with a workaround. Needs a proper fix.
2. https://github.com/akvo/akvo-flow/issues/3171

**Comment by janagombitova** [comment]
As the work here is done, I am closing the issue
