### ISSUE TITLE
Consistent notifications for validation of assignments

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#3221]
When creating assignments and there are some error conditions, we notify the users but using different styles. In some cases with a dialog box and in others with highlights.  We should ideally make the notifications consistent.  + We previously decided on highlights instead of dialog boxes.

![assignment-notifications](https://user-images.githubusercontent.com/533336/66555407-e98fc280-eb4e-11e9-9ad3-9a40a284987d.gif)

**Comment by janagombitova** [comment]
@Kiarii can you specify how best to go about this. We agreed on highlights instead of dialogue boxes but what do you mean by highlights? Is it just to outline the field in red? Should it also have a text with it? Etc? Thanks

**Comment by Kiarii** [comment]
here are some pointers: 

- <s> if the user hits [save] while some field remains incomplete, the UI in addition to showing to an error should actually scroll the page up bringing in view the respective fields; with the the top most being the priority (of the view) </s>
- error message should ideally be presented under the respective fields or else the section titles, when input for forms or devices are sections and not single fields..
- error messages and highlights are applicable, I suggest we keep error message as the default since they will work both for single fields and section-ed-input such as form selections ..
- lets use some direct language when we point to whats missing, to make it easier for the user to understand whats amiss and what needs doing e.g. "Set assignment duration" in place of "The from or to date has not been set", and the in-field text might say "pick a date" in place of "Invalid date", and so on

**Comment by janagombitova** [comment]
Closing this issue as it is no longer relevant
