### ISSUE TITLE
Assignments - Small UI improvements 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3285]
After our talk just now, @marvinkome can you add: 
* device counter 
* change 'No forms..' to 'No published forms...'

![Screen Shot 2019-11-08 at 10.35.40.png](https://images.zenhubusercontent.com/5c8f6c3ea7f08c1a3af97cc1/77ba2657-a371-49a6-9a63-9ed889872571)

**Comment by muloem** [comment]
Another small issue here:

When selecting the group of devices, its possible to open up the group by clicking on the device group name.  However, the rest of the section next to the device group name appears to be clickable but nothing happens when you click. same for the arrow at the extreme right end of the accordion.

![assignments-ui-dropdown](https://user-images.githubusercontent.com/533336/68477185-0b9f6200-022d-11ea-931a-3515a562488f.gif)

**Comment by janagombitova** [comment]
And one more :) 

I was looking at the mock-up and the form selector should **not** be checkboxes but radio buttons. So you turn a form on leave it turned off. Can you make the change? thanks

**Comment by janagombitova** [comment]
Hey Marvin, I had the feeling we had this already in an issue, but here I go again: Can you remove the text: `Only enabled forms can be submitted`?  This is actually not correct in terms of how the assignments work

**Comment by janagombitova** [comment]
The remaining points will be handled in #3290

**Comment by muloem** [comment]
All done! 👍
