### ISSUE TITLE
Redesign assignments to accommodate assigning data points 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3297]
We have been working on redesigning and improving assignments to allow to assign data points per device. To accommodate this new functionality we need to change the layout of the assignments screen. 

![image](https://user-images.githubusercontent.com/12456965/68751585-1fb6db00-0602-11ea-8a00-3db63295a546.png)

We will add a static side panel (in line with the recent Lumen designs and RSR - yaay more product alignment) where Salim will first change the assignment settings under Forms, then select and add devices under Devices and then add data points to devices.

**Comment by janagombitova** [comment]
The final mockups are here: https://projects.invisionapp.com/share/5YUUUPXF7DA#/screens

**Comment by valllllll2000** [comment]
Works perfectly just one minor detail, see screenshot:
![Screenshot from 2019-12-17 11-35-29](https://user-images.githubusercontent.com/923280/70988065-6ac08400-20c1-11ea-9593-6f07eae6c7fb.png)
This is slightly different from the original mockup in a way that once the section is selected, for instance forms, the text should be black. But in the current implementation the text is always blue. If I understand correctly blue means selectable but since we already selected it it should not be "selectable". This is a minor cosmetic issue, feel free to open another issue for it as I do not think this should block the release.

**Comment by valllllll2000** [comment]
everything else works fine! opened another issue for the minor difference from mockups
