### ISSUE TITLE
Jackson XML publishing missing elements/attributes

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#3316]
The newly implemented Jackson XML publishing from #3115 has some attributes missing or wrongly configured.  We will track and fix them here

- [x] the `registrationSurveyId` attribute is missing from the `<survey></survey>` element
- [x] when set Variable name: variableName="SomeVar" is missing from xml
the expected would be `<question order="1" type="free" mandatory="true" localeNameFlag="false" id="381322013" variableName="SomeVar">`
- [x] the `app` attribute is missing from the `<survey>` element
- [x] Options renderType="radio" is missing but it is not used on the app
- [x] Also `allowMultiple` is not set for option questions.
- [x] Barcodes: when we select allow multiple barcodes this does not work on the app, the flag `allowMultiple="true"` is not set. Do we actually need multiple Barcode scans in one question?
- [x] `repeatable` attribute for `QuestionGroup` is set even in cases where its false.  We dont include it when its false.

**Comment by muloem** [comment]
> Do we actually need multiple Barcode scans in one question?

We will have to evaluate that but for now maintain the functionality as was.

**Comment by janagombitova** [comment]
@muloem to react to your question: 
> Do we actually need multiple Barcode scans in one question?

I say no mostly because we should stick to the rule, one answer = one value, so if you need to scan more things, that should be handled with multiple barcode questions. I am also not sure how barcodes are actually used in the field. I only know one case where: the barcode is attached to an e.coli water quality sample bag and the code is scanned to Flow, so after the incubation time you can register the result to the proper data point. 

Ideally, we would check if and how this question type is used on partner instances and limit to only one barcode per answer (if the data proves this assumption right)

**Comment by stellanl** [comment]
Which allowMultiple is not set for option questions? Pressty sure the one in the options Container is set.

**Comment by valllllll2000** [comment]
There are still some difference 
#### Do not supposed any issues on the app:
-[ ] registrationSurveyId attribute is missing from the <survey></survey> element, this item is also missing from 10.1 version
-[ ] repeatable attribute for QuestionGroup is set even in cases where its false. We dont include it when its false.

**Comment by muloem** [comment]
I feel pretty certain that I did the work on `registrationSurveyId`.  I will crosscheck that

**Comment by valllllll2000** [comment]
All fixed!
