### ISSUE TITLE
Show number of datapoints assigned for a device

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#3496]
# Context
We introduced the new datapoints assignment functionality that, by default, assigns all datapoints in a monitoring survey to every device added to the assignment. 

# Problem or idea
When this "assign all datapoints" option is selected, we have no clue how many datapoints have been assigned to a device.  We also do not want to download all the datapoints from the backend to handle that processing in the frontend, i.e .just to count how many of the datapoints are assigned.

# Solution or next step
Have the backend return a count of the number of datapoints associated with a survey?

**Comment by iperdomo** [comment]
This is a new requirement, right? In the previous state of assignments, the user also didn't know how many datapoints were assigned.

Thinking on implementation, giving no numbers is _better_ than reporting wrong numbers. IMHO

We know we can't do a `SELECT count(*) FROM datapoints WHERE surveyId = ?`, in order to not _waste_ a load of all and then throwing away just for counting, we need to cache the count, and we know how that will go (:point_down: just to link to some count related issues)
* https://github.com/akvo/akvo-flow/issues/682
* https://github.com/akvo/akvo-flow/issues/644

**Comment by janagombitova** [comment]
This is a handy change. Works well as far as I can tell on uat2

**Comment by janagombitova** [comment]
If all is done, please close the issue
