### ISSUE TITLE
Cannot see submissions in Inspect data tab

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3627]
A partner reported an issue when cleaning data via the Inspect data tab. After selecting a submission the data does not load. I reproduced the issue on greendeal.akvoflow.org but pilots.akvoflow.org and uat1.akvoflow.org worked fine for me.

<img width="1250" alt="Screen Shot 2020-08-18 at 11 15 00" src="https://user-images.githubusercontent.com/12456965/90495549-0882bc00-e145-11ea-85d2-16c28fbbf874.png">

I checked further on the instance and other survey forms worked also fine. It seems this particular one is having issues. The survey form is: NMVB Monitoring > Voedselbos Monitoring > Registratie Voedselbos

**Comment by janagombitova** [comment]
Here is what I did: 

1. go to greendeal.akvoflow.org
2. go to Inspect data 
3. select NMVB Monitoring > Voedselbos Monitoring > Registratie Voedselbos
4. click on any submission 
5. the loading does not end and the data does not show 

However, if you try the same steps on a different production instance, it works fine. Also if you reload the GreenDeal one and try to same but for a different form, it also seems to work fine.

**Comment by marvinkome** [comment]
Checking the response from the server, I can see some values are strings even though they're supposed to be JSON.

![Response](https://user-images.githubusercontent.com/30107382/90499186-24845e80-e141-11ea-857c-aa1010cedb59.png)
![Error](https://user-images.githubusercontent.com/30107382/90499219-2fd78a00-e141-11ea-910c-0481de1683fe.png)

**Comment by valllllll2000** [comment]
After checking the data on the app, it turns out there is a Cascade (question 2 of the registration form) it has a missing code so the app and dashboard are unable to process it. What needs to be done is 
* fix the Cascade question responses. Maybe it was a text before or maybe the data cleaning was not done properly and they forgot to add the code.
* should the cleaning logic when importing check if the data is correct and maybe fail if the unexpected format is inserted?
* the UI in the app, we still display the question, without the answer. In my opinion, since users can insert any data, the client UI should check and at least show an error message that something is wrong with the data.

**Comment by janagombitova** [comment]
The details were communicated to the partner and how they can clean the data. Closing the issue. Valeria's comments are valid and we can discuss them in the future.
