### ISSUE TITLE
After assigning more than 710 data points the assignment do not load the list after reopening

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3629]
Issue reported today by Ecosia: 

>... Indeed, with a relative few points, it seems to work. But for example, When I try a specific case to assign 1611 specific it still does not seem to work. I do these steps within this particular case:

> 1) Click on assing datapoints >> By data point name of ID
> 2) I search on all sites for contract `10` (so I enter `10 -` as search criteria and press enter)
> 3) I select all sites (select all 1611 points)
> 4) Click on assign and then on save. All seems well.

> Then all the 1611 points seem to be attached to the device. I click on save and the system directs you back to the main overview after saving. However, if I go back to the device to check the assigned points, the system keeps on ‘thinking’. It also shows “0 data points assigned”. It might be due to the number of points, but it keeps ’thinking' ‘foreever’.

I tried a few cases, with 710 points assigned, all works fine. Then I tried 922 points assigned and the loading does not stop. In Console we get `413 error` 

<img width="1198" alt="Screen Shot 2020-08-26 at 14 55 44" src="https://user-images.githubusercontent.com/12456965/91306015-3f437c80-e7ac-11ea-9c88-2c51a761faef.png">

The specific form is ecosia.akvoflow.org > TREE PLANTING IMPACT > Planting site registration and monitoring > Planting site registration

**Comment by muloem** [comment]
@marvinkome there is still some more stuff to be done here.  Findings after some quick tests

 - when all data points have been assigned and one unassigns them in order to assign specific ones, then the load more button appears when it shouldn't be there yet.  It should only appear when there is a long list of datapoints (more than 30) for a particular device

- the datapoint information in the list (in the side bar) when retrieved is cut off so its not possible to see the identifier.
<img width="469" alt="image of datapoint list with identifier cut off" src="https://user-images.githubusercontent.com/533336/92992563-31039900-f4ec-11ea-9f81-db089774e90c.png">


- after searching for datapoints to be assigned, when trying to assign them, i get an exception.
<img width="729" alt="image of exception when trying to assign datapoints" src="https://user-images.githubusercontent.com/533336/92992573-48428680-f4ec-11ea-9517-051f59543a4b.png">

**Comment by iperdomo** [comment]
![assignments](https://user-images.githubusercontent.com/178474/93349171-74853c80-f837-11ea-85b2-63fe6f9e0385.gif)

As commented in the internal chat, the _Load more_ button needs to be available in Edit mode, otherwise the user is only able to select the pre-loaded list of data points.

**Comment by janagombitova** [comment]
released
