### ISSUE TITLE
Limit the number of monitoring submissions download with data points 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3645]
# Context
Currently, when data points are assigned for monitoring and downloaded to the Flow app, previous submissions for the assigned monitoring forms and the data are downloaded with the data points. This functionality was created to give the enumerator background information on the data point and context to what data was previously submitted. It is also used for the feature to `prefill data` that add previously submitted answers to a new monitoring form submission. 

# Problem
However, with monitoring scaling, more and more data points are being assigned and all the previous submissions are being downloaded causing timeout issues. The more data users collect the more this issue will grow.

It also brings up the question, does Al need to have all the old data on his device? Does he need all of it? For what reason? Is it secure? Does it not cause biased entries? 

# Opportunity 
We need to ensure Flow can work on a large scale what however may mean we need to limit what data users get on their device, especially if it is not used/needed. 

## Research 
We asked a few users the following questions: 
* Does the enumerator need to have all previous submissions? 
* What do they use this data for (if they use it)? 

**User A**
>  Actually, I was not aware of this. So good that you mention it. Well, maybe it is even an advantage if the enumerator does not know the previous submission values, as this makes it more sure that the new submission is not influenced by previous submissions. So, I would limit it indeed to the last one. Then at least no trends can be seen and the enumerator is fully unbiased.

**User B**
> I think there are different use cases. For example, if it's quarterly monitoring, there might still be a need to see what happened in q1. But then for other partners, they might not need it at all. So it's a bit tricky and case-specific. And usually cases I have seen it is to see a value from the past, for example on agricultural products, or on types of crops they were cultivating at y1. Or just to see how if a point has been monitored already. But the data isn't been used. 

**User C**
> It could be good to have the previous submissions for reference, but I haven't particularly found a real case as of now. But can think of something like checking the functionality of water point for the enumerator reference and probe specific questions based on this information. But then the survey might need to actually be set up differently and have questions in the monitoring form depend on previous answers. 

## Idea 
As of now, it seems the historical data is not actively used. 

We could decide to limit the number of submissions downloaded per assigned form with the data points. For example, we, by default, only download the last and the first and indicate in the app in History that there is a total of XYZ forms submitted. Or only the last submissions. Or none. Later on, we could provide the option for Salim when assigning data points to decide if for this form all previous submissions need to be sent too. Or other options...

**Comment by Kiarii** [comment]
My 2 cents and thought for food:
- On a side note, this brings to mind the concept of [a datapoint profile](https://invis.io/HUPMLWTAMYS#/333898261_1-_Dp_Profile) (old sideproject) 🛠; the main assumption being that when Alp. is sent out to monitor datapoints the core requirement with whatever data is pushed to the device is to be able to correctly identify a datapoint before submitting respective monitoring data. ☝🏾

- The use case of referring to previously submitted data doesn't really stand out (at least in my assumption), if you are sent out to measure the water quality or crops in the garden, the previously submitted water quality or crops dont really impact/inform your assignment, even when subsequent monitorings are done simultaneously (2 monitorings submitted at the same time) because of logistic issues. Strictly speaking, data comparison/reference/analysis should not happen on the device 🤷🏾‍♂️ Needless to say,  we should focus on data collection 

- To take this a step further, not all registration data may be necessary (to sync to the device for monitoring assignments), the key is datapoint identifying facets.. which is why I digressed in my opening comment to mentioning a datapoint profile. I am not saying that the registration data be split up but insinuating that we should reorganize a datapoint's identifying info - profile - to make datapoint id easier by deemphasizing secondary information

- Another point-of-interest for mua is the concept of assigning surveys versus assignments; if we assign a survey, we are obliged - at least in theory - to push all accompanying data to the device. In comparison, if we talk about assignments, then we can narrow down on the data - datapoint identifying and respective monitoring forms - pushed to the device.. I am not Alp. but I still find it weird that in Flow db I add my device to an assignment, but on the device, I have to refer to the survey name to identify what tasks I assigned myself. 📲 At the back of me mind am still expecting to find the assignment name in the device 🤦🏾‍♂️

**Comment by janagombitova** [comment]
Just to recap the current status from the stand-up: We now send the last 3 submissions made to an assigned monitoring form. If there are more monitoring form submissions made to an assigned form, we do not send them to the app. 

@iperdomo Is this correct? ^^ 

In the future, we will need to rethink if having old submissions is needed or not.

**Comment by iperdomo** [comment]
> Just to recap the current status from the stand-up: We now send the last 3 submissions made to an assigned monitoring form. If there are more monitoring form submissions made to an assigned form, we do not send them to the app.

What we send is the 3 most recent submissions + the registration submission, **not** the most recent submissions of the assigned forms. See the issue raised early this year: https://github.com/akvo/akvo-flow/issues/3528 - Limiting the data to assigned forms was reverted after a review from @valllllll2000
