### ISSUE TITLE
Flow survey publishing issues

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow#3795]
# Context
The publish button sometimes is enabled when everything has already been published.
Publishing is sometimes slow.

# Problem or idea
The way the code is written it seems tricky to understand what is happening and when the button is enabled or disabled.
Step 1 is to refactor the publishing button display to have a better control of when it is enabled or not

**Comment by janagombitova** [comment]
I would like us to use this issue as the Epic for publishing work. All changes should we kept small and pushed out as soon as possible via separate issues, but this issue can be used to keep an overview of the discussion and larger decisions. 

# Context 
The current implementation of publishing forms has been causing issues. It is not only the fact that it takes a long time to complete and a lot can be improved behinds the scenes but also the current user workflow creates problems down the road. 

## How publishing works today  
Petra is working on a survey form. This form is currently in draft. She is adding in questions and making changes to the form structure. Once she is done with the form draft and it is ready for data collection she needs to publish it. By publishing, she indicates that the form is no longer in the draft stage but is now ready for enumerators to use. She hits on the publish button in the form and then gets a message telling her that she needs to go to the Messages tab to see that the publishing is completed. Now she is expected to leave the page. 

## Why are we prioritising this issue
There are many improvements we can make to Flow, but we decided to handle this issue: 
* Working on the survey editor is the 1st step our users take when working with Flumen, and publishing is a core task to complete to start data collection. So it needs to work clearly and smoothly to ensure users can collect data and also have a positive impression of Flumen 
* Increase in support coming in due to the issue: since we handled issues around checking dependencies and deleting monitoring submissions this is the highest support topic. Handling it will improve user impression and also reduce time spent on support for us 

# Known issues 
- Once Petra hits the publish button she needs to go to the Messages tab to see the result --> this is unneeded extra navigation for her and many of our users forget this step  
- Once she hits publish, she should navigate away from the form and not make further changes to the form. However, sometimes she hits publish and remains on the form page and edits another question, or makes another change. --> Then the form version does not update properly and this causes issues with which change is published and which is not. 
- There is no visual indication of the form being published beside the disabled publish button. 
- Publishing takes a long time to complete 
- Publishing silently fails: https://github.com/akvo/akvo-flow/issues/3805
- Publishing fails due to translations: https://github.com/akvo/akvo-flow/issues/3628
- Form version does not always update: https://github.com/akvo/akvo-flow/issues/3619

# Next steps 
* Discuss solution - https://app.mural.co/t/akvo3857/m/akvo3857/1622534790183/d04c7dd8338e0cb20fbdefaf5444c56f8dc45621
* Break down into implementable small chunks 
* Consider redesign of how we show survey and forms setting to declutter the UI

**Comment by Kiarii** [comment]
Some thought for food or food for thought as it were:
**on Publishing**
- According to Isha, besides publishing to make the form deployable to devices, in their workflow (and partners' workflow according to her) an internal review is done on forms to test out dependencies, validate translations, and ensure consistency, by Petras within Akvo or Partner organization. One reason why this is the case is that not all internal reviewers have access to the Flow dashboard specific survey - and in any case, testing out the form on the device is more practical and closer to the real thing and being on the dashboard. She cited a 450 question Idh form as an example; we do not have a graceful way to review such huge forms in the dashboard (and even though now webforms might provide some usability, they do not cover all question types).
- One of the ideas we had for making waiting for the publishing process tolerable for users (esp if it happens within a min or a little bit over was to lock the screen so that the Petra cannot make further changes to the form while the publishing process still runs in the background; either with a modal dialog that gives varying tips about running a data collection project or using Flow. If the process with huge forms takes more than say 2 mins we could suggest to Petra that she do something else in the meantime. Isha felt that the the later case would be impractical because it breaks the workflow; i.e. Petra publishes a form so she can do something with it..
- On a side note, Isha also noted that copying long surveys also takes too long and she has to refresh the page more than once to have all new copied questions rendered
- Another side note about publishing was to rethink the terminology and to communicate form status as well e.g. A draft (status) form can be published with a Publish action, and a changes can be made into a published (status) form with an Update action. Furthermore a published (status) form can be Unpublished, or reverted to draft.. The later, Isha said she has not thought about such an action; usually if they want to make a form unavailable for data collection, they will either archive or delete it.

**Comment by janagombitova** [comment]
@valllllll2000 @muloem and @Kiarii and I discussed this issue today and added the proposed workflow (in green) in the mural. 

## Next steps 
1) go through validation at publishing and make sure we validate everything before we start publishing
2) go through the publishing and optimise to reach less than 1 minute for a 1000 option question form with 1 translation
3) improve the visibility to the user of publishing - draft state - etc 
4) change the survey and form settings grey boxes that we have today 
5) change the UI for publishing

**Comment by janagombitova** [comment]
For the sake of keeping all decisions in one place, there is an update from @muloem on the status: 

We've split the work up as follows

Frontend work to assemble the form into a single object and post to the backend
Backend work to process the received object then generate XML
Backend to add translations to the XML
Cascade - we can fill in any missing info if needed
Emmanuel Mulo: And identified these approaches to handle the publishing

actually 3 options:
1) Client requests load translations when opening form detail same as all data
2) Client requests load translations when user presses publish and then sends it all to backend
3) Client does not send translations but backend before publishing loads the translations

Emmanuel Mulo: We decided to try out number 3 - because its a subset of number 2. if it works fine then we're good to go. if not we additionally handle the translations on the client side

**Comment by Kiarii** [comment]
In line with the ideated simplification form / survey editor, publishing process is handled in situ and even more is made explicit to the user: here the assumption is that we are able to publish forms in under a min 🤺 
<img width="1273" alt="Screen Shot 2021-06-18 at 12 00 50" src="https://user-images.githubusercontent.com/12692444/122536087-d5db7580-d02c-11eb-8069-ee77cad79551.png">

This way we make communication
- process status
- process end result; success incl. form version and failure: provide Retry
- see the ideated workflow in the [wireframe mockup](https://invis.io/ZB116ELJVM9K#/453783171_26-0_Publishing_Initiated)
