### ISSUE TITLE
Add labels to option questions options

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#828]
The aim is to add a value to question options, in the same way as HTML options have a label and a value. The main purpose for this is to make it easier to import FLOW data into existing databases. The label would be used for display, the value will be used for in API's or optionally in data exports.

In many cases, existing databases use coding schemes to codify answers to questions. For example, 'yes' might be 1, and 'no' might be 0. Another example could be 'banana'=01, 'orange'=02, 'grapefruit'=03.

Implements https://github.com/akvo/akvo-product-design/issues/34

**Comment by muloem** [comment]
@mtwestra did you already push the code done so far for this one?

**Comment by mtwestra** [comment]
@muloem, no, not yet. In need to clean it up and merge it to the current develop. That will take about 0.5-1 day of work

**Comment by jonase** [comment]
## (pre) Test Plan

This issue is not feature complete yet but we have added some initial support for Option codes in exports. There should be no user visible changes when exporting reports with option questions and if there are, it should be regarded as a regression.

**Comment by rumca** [comment]
@jonase is this for the 1.9.4 milestone?

**Comment by jonase** [comment]
@rumca Yes we pushed the report part of the codes for options to 1.9.4.

**Comment by jonase** [comment]
## Test Plan (reporting)

Option questions can be configured to `Allow other?`, `Allow multiple?`, and `Use codes?` (9 combinations in total). 
* For each combination create a separate option question
* Submit a few responses. 
  * For `Allow other?` questions make sure you add an “other” response for some of the submissions (but not all). 
  * Leave some questions unanswered
* Generate a raw data report
  * Multiple responses should be pipe separated: `Foo|Bar|Baz`
  * Responses with codes should be colon separated: `1:ABC|4:JKL`
  * There’s no definite way of knowing if the last response is an “other” or not.
* Clear the md5 hash column in order to import all responses
* In the data cleaning tab, choose the form and upload the excel file
* Check the datastore,
  * Each response should be JSON encoded with a “text” property (and a “code” property for the “Use codes?” questions)
  * The `isOther` flag should be preserved for responses where “other” was used.
  * Any changes you made to the responses should be visible in the datastore.

**Comment by rumca** [comment]
@muloem I think one of the above commits has borked the option codes & saving options in general. It was definitely working before, but now it appears when I add some options to an option question and then click save that they're all just discarded?

**Comment by rumca** [comment]
@jonase not sure if you've got any time to have a look at this, think it might be a small enough fix though. On the inspect data tab when you've submitted an ``other`` option we don't display anything:

![screen shot 2016-01-05 at 11 47 52](https://cloud.githubusercontent.com/assets/3003031/12114503/4d2da674-b3a2-11e5-9caf-1418d973d89d.png)

**Comment by jonase** [comment]
@rumca Is the "other" option never shown? What happens when you have "allow multiple" enabled?

**Comment by rumca** [comment]
The "other" response is correctly downloaded in the raw data reports etc, so I'm guess it just isn't being displayed on this tab. In both cases where I've allowed "other" here, it's not being displayed (one question allows multiple and the other doesn't).

**Comment by rumca** [comment]
Same thing on the monitoring tab:

![screen shot 2016-01-05 at 11 58 47](https://cloud.githubusercontent.com/assets/3003031/12114682/b4f814d2-b3a3-11e5-86c6-9d6861b8f55a.png)

**Comment by rumca** [comment]
(I think) Everything works as intended now, haven't been able to break it in a noticeable fashion anyway :+1:
